In [1]:
import pandas as pd
import numpy as np

In [2]:
location = "datasets/DC_Properties.csv"
df = pd.read_csv(location)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [4]:
df.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [5]:
df_missing=pd.read_csv (location)
df_missing.head ()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [6]:
df_missing.isnull().sum ()

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY                   52906
STATE                  52906
ZIPCODE                    1
NATIONALGRID           52906
LATITUDE                   1
LONGITUDE                  1
ASSESSMENT_NBHD            1
ASSESSMENT_SUBNBHD     32551
CENSUS_TRACT               1
CENSUS_BLOCK           52906
WARD                       1
SQUARE                     0
X                        237
Y                        237
QUADRANT                 237
dtype: int64

In [7]:
missing= df_missing ['ASSESSMENT_SUBNBHD'].isnull()
df_missing.loc [missing]

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
92,92,2,0,Hot Water Rad,N,1.0,7,4,1909.0,NaN,...,-77.048449,Foggy Bottom,NaN,10800.0,010800 3004,Ward 2,81,-77.047880,38.897076,NW
93,93,2,3,Hot Water Rad,N,1.0,12,6,1898.0,2000.0,...,-77.048508,Foggy Bottom,NaN,10800.0,010800 3004,Ward 2,81,-77.047880,38.897076,NW
257,257,1,1,Forced Air,Y,1.0,4,2,1900.0,1956.0,...,-77.052674,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
258,258,1,1,Forced Air,Y,1.0,4,2,1900.0,1956.0,...,-77.052625,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
259,259,2,0,Forced Air,Y,2.0,6,3,1900.0,1996.0,...,-77.052537,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
260,260,2,0,Hot Water Rad,N,2.0,6,2,1900.0,NaN,...,-77.052489,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
261,261,1,0,Forced Air,Y,1.0,6,2,1900.0,1998.0,...,-77.052347,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
262,262,3,0,Warm Cool,Y,3.0,9,3,1886.0,2010.0,...,-77.052312,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
263,263,2,1,Forced Air,Y,1.0,5,3,1910.0,2004.0,...,-77.052887,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
264,264,1,0,Hot Water Rad,N,1.0,6,3,1900.0,2014.0,...,-77.052914,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
265,265,1,1,Warm Cool,Y,1.0,5,2,1900.0,2001.0,...,-77.052941,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
266,266,1,0,Hot Water Rad,N,1.0,4,2,1900.0,1954.0,...,-77.052962,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
267,267,1,0,Warm Cool,Y,1.0,4,2,1900.0,1956.0,...,-77.052986,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
268,268,2,0,Warm Cool,Y,1.0,6,2,1900.0,2004.0,...,-77.053130,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
269,269,1,0,Forced Air,Y,1.0,4,2,1900.0,2002.0,...,-77.053097,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
270,270,1,0,Hot Water Rad,Y,1.0,4,2,1900.0,2008.0,...,-77.053103,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
271,271,1,0,Forced Air,Y,1.0,4,2,1900.0,2009.0,...,-77.053103,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
272,272,1,0,Hot Water Rad,N,1.0,5,2,1889.0,NaN,...,-77.053097,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
273,273,2,0,Hot Water Rad,Y,1.0,4,2,1900.0,2001.0,...,-77.053081,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
274,274,1,0,Warm Cool,Y,1.0,4,2,1900.0,2002.0,...,-77.053084,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
383,383,2,1,Warm Cool,Y,1.0,7,2,1900.0,2007.0,...,-77.053075,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
384,384,2,0,Warm Cool,Y,1.0,7,2,1900.0,2007.0,...,-77.053007,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
385,385,4,1,Forced Air,Y,1.0,9,6,1900.0,2003.0,...,-77.053112,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
386,386,2,1,Forced Air,Y,1.0,6,2,1900.0,1960.0,...,-77.053042,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
387,387,2,2,Warm Cool,Y,1.0,7,2,1900.0,2001.0,...,-77.052878,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
388,388,2,2,Warm Cool,Y,1.0,6,2,1900.0,2015.0,...,-77.052825,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
389,389,2,2,Warm Cool,Y,1.0,4,2,1957.0,1995.0,...,-77.052930,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
390,390,2,2,Warm Cool,Y,1.0,6,3,1950.0,1997.0,...,-77.052979,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
391,391,1,1,Forced Air,Y,1.0,4,2,1900.0,2004.0,...,-77.052392,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
392,392,2,1,Forced Air,Y,1.0,5,2,1960.0,2000.0,...,-77.051746,Foggy Bottom,NaN,5600.0,005600 4004,Ward 2,30,-77.051722,38.900391,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158869,158869,2,0,Warm Cool,Y,NaN,7,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158870,158870,2,0,Warm Cool,Y,NaN,7,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158871,158871,1,0,Warm Cool,Y,NaN,4,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158872,158872,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158873,158873,1,0,Warm Cool,Y,NaN,4,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158874,158874,1,0,Warm Cool,Y,NaN,4,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158875,158875,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158876,158876,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158877,158877,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158878,158878,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158879,158879,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158880,158880,1,0,Warm Cool,Y,NaN,4,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158881,158881,1,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158882,158882,2,0,Warm Cool,Y,NaN,7,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158883,158883,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158884,158884,1,0,Warm Cool,Y,NaN,4,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158885,158885,2,0,Forced Air,Y,NaN,4,2,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158886,158886,1,0,Forced Air,Y,NaN,2,0,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158887,158887,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158888,158888,1,0,Forced Air,Y,NaN,4,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158889,158889,1,0,Forced Air,Y,NaN,4,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158890,158890,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158891,158891,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158892,158892,1,0,Forced Air,Y,NaN,4,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158893,158893,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158894,158894,2,0,Forced Air,Y,NaN,5,2,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158895,158895,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158896,158896,1,0,Forced Air,Y,NaN,3,1,2006.0,NaN,...,-77.024908,Central-tri 3,NaN,5800.0,NaN,Ward 2,377,-77.024910,38.896742,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [8]:
#descriptive statistics
df.describe ()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
count,158957.000000,158957.000000,158957.000000,106696.000000,158957.000000,158957.000000,158686.000000,80928.000000,158957.000000,106652.000000,...,158957.000000,158957.000000,52261.000000,52261.000000,158956.000000,158956.000000,158956.000000,158956.000000,158720.000000,158720.000000
mean,79478.000000,1.810678,0.458237,1.198039,6.187736,2.732506,1941.987579,1998.243537,1963.718024,2.091793,...,14.252999,2473.282158,2371.544249,888.834542,20012.694563,38.914854,-77.016676,5348.216324,-77.016712,38.914846
std,45887.077707,0.976396,0.587571,0.596924,2.618165,1.358864,33.640234,16.575786,24.923150,2.933323,...,3.725736,5059.046023,1114.272364,420.185822,15.627084,0.031723,0.040938,3369.645953,0.040933,0.031682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1754.000000,20.000000,1800.000000,0.000000,...,11.000000,0.000000,1001.000000,0.000000,20001.000000,38.819731,-77.113909,100.000000,-77.113135,38.820576
25%,39739.000000,1.000000,0.000000,1.000000,4.000000,2.000000,1918.000000,1985.000000,1954.000000,2.000000,...,11.000000,697.000000,1501.000000,616.000000,20007.000000,38.895425,-77.042892,2102.000000,-77.042894,38.895432
50%,79478.000000,2.000000,0.000000,1.000000,6.000000,3.000000,1937.000000,2004.000000,1963.000000,2.000000,...,13.000000,1649.000000,2265.000000,783.000000,20011.000000,38.915337,-77.019596,5201.000000,-77.019581,38.915229
75%,119217.000000,2.000000,1.000000,1.000000,7.000000,3.000000,1960.000000,2010.000000,1975.000000,2.000000,...,17.000000,3000.000000,2910.000000,1060.000000,20018.000000,38.936075,-76.988626,8302.000000,-76.988842,38.936077
max,158956.000000,14.000000,11.000000,6.000000,48.000000,24.000000,2019.000000,2019.000000,2018.000000,826.000000,...,117.000000,942632.000000,5621.000000,8553.000000,20392.000000,38.995540,-76.909758,11100.000000,-76.910511,38.993646

In [9]:
df['PRICE'].mean()

931351.5949336156

In [10]:
df['PRICE'].max()

137427545.0

In [11]:
df['PRICE'].min()

1.0

In [12]:
df.groupby(['AYB', 'SALEDATE', 'PRICE']).mean()

                                      Unnamed: 0  BATHRM  HF_BATHRM  \
AYB    SALEDATE            PRICE
1754.0 2016-08-23 00:00:00 7100000.0     37034.0     7.0        2.0
1765.0 2016-08-02 00:00:00 1100000.0     19576.0     2.0        1.0
1776.0 1998-07-22 00:00:00 223500.0       5128.0     3.0        0.0
       2009-04-17 00:00:00 725000.0       5130.0     2.0        1.0
1780.0 2016-04-04 00:00:00 825000.0      21630.0     1.0        1.0
       2016-09-22 00:00:00 660000.0     112869.0     2.0        1.0
       2016-10-25 00:00:00 830000.0     112870.0     2.0        1.0
1790.0 1996-01-19 00:00:00 812500.0      18326.0     2.0        0.0
       2015-06-29 00:00:00 2549000.0     20766.0     3.0        1.0
       2017-08-24 00:00:00 1175000.0     19614.0     2.0        0.0
1794.0 2013-08-13 00:00:00 1550000.0     19606.0     3.0        0.0
       2017-05-24 00:00:00 5250000.0     19304.0     5.0        1.0
1796.0 2009-11-04 00:00:00 3330000.0     34319.0     5.0        1.0
       2011-11-01 00:00:00 3950000.0     19879.0     3.0        1.0
1800.0 1995-10-20 00:00:00 233000.0     111394.0     1.0        1.0
       1997-10-20 00:00:00 339500.0         37.0     2.0        2.0
       2005-06-07 00:00:00 220700.0     145507.0     1.0        0.0
       2005-06-15 00:00:00 166000.0     148574.0     1.0        0.0
       2005-06-29 00:00:00 155000.0     148576.0     1.0        0.0
       2006-08-28 00:00:00 1050000.0        40.0     3.0        1.0
       2006-11-21 00:00:00 285000.0       4825.0     1.0        0.0
       2008-09-04 00:00:00 535000.0      13924.0     2.0        0.0
       2011-03-18 00:00:00 846000.0         46.0     3.0        1.0
       2012-07-31 00:00:00 220000.0     144901.0     1.0        0.0
       2012-09-12 00:00:00 380000.0     144902.0     2.0        0.0
       2012-10-11 00:00:00 220000.0     145505.0     1.0        0.0
       2012-12-11 00:00:00 7000000.0     19110.0     4.0        1.0
       2013-05-03 00:00:00 270000.0     144904.0     1.0        0.0
       2013-05-16 00:00:00 322000.0     145508.0     1.0        0.0
       2013-06-13 00:00:00 235000.0     148573.0     1.0        0.0
...                                          ...     ...        ...
2018.0 2018-05-04 00:00:00 462900.0      99131.0     3.0        1.0
       2018-05-10 00:00:00 462900.0      99129.0     3.0        1.0
                           464000.0      99130.0     3.0        1.0
                           468000.0      99132.0     3.0        1.0
       2018-05-14 00:00:00 803295.0      79968.0     3.0        1.0
       2018-05-23 00:00:00 408855.0     104256.0     3.0        1.0
       2018-05-31 00:00:00 460090.0     104257.0     4.0        1.0
       2018-06-01 00:00:00 459900.0      91741.0     3.0        1.0
                           1952500.0     31760.0     4.0        1.0
       2018-06-06 00:00:00 438690.0     104258.0     3.0        1.0
       2018-06-08 00:00:00 445155.0     105579.0     3.0        1.0
       2018-06-19 00:00:00 435200.0      91747.0     2.0        2.0
                           439900.0      91742.0     2.0        2.0
                           457100.0      91743.0     2.0        2.0
                           457700.0      91744.0     2.0        2.0
       2018-06-21 00:00:00 419000.0     104259.0     3.0        1.0
       2018-06-27 00:00:00 460385.0     105691.0     4.0        1.0
                           462000.0     105578.0     4.0        1.0
       2018-06-28 00:00:00 405000.0      91044.0     3.0        1.0
                           435000.0      91155.0     3.0        1.0
                           599000.0      93328.0     3.0        1.0
       2018-06-29 00:00:00 457100.0      91745.0     2.0        2.0
       2018-07-02 00:00:00 465600.0     101609.0     3.0        1.0
       2018-07-03 00:00:00 451400.0     101612.0     3.0        1.0
                           459900.0     101931.0     3.0        1.0
       2018-07-05 00:00:00 449900.0     101611.0     3.0        1.0
                           499900.0     101610.0     3.0        1.0
       2018-07-09 00:00:00 479000.0      98835.0     2.0        2.0
       2018-07-12 00:00:00 200000.0      93153.0     2.0        0.0
                           560000.0      94748.0     3.0        1.0

                                      NUM_UNITS  ROOMS  BEDRM  YR_RMDL  \
AYB    SALEDATE            PRICE
1754.0 2016-08-23 00:00:00 7100000.0        1.0   14.0    8.0   1983.0
1765.0 2016-08-02 00:00:00 1100000.0        1.0    4.0    2.0   1999.0
1776.0 1998-07-22 00:00:00 223500.0         2.0    5.0    3.0   1984.0
       2009-04-17 00:00:00 725000.0         1.0    6.0    4.0   1998.0
1780.0 2016-04-04 00:00:00 825000.0         1.0    5.0    1.0   1986.0
       2016-09-22 00:00:00 660000.0         NaN    5.0    2.0   2016.0
       2016-10-25 00:00:00 830000.0         NaN    5.0    2.0   2016.0
1790.0 1996-01-19 00:00:00 812500.0         1.0    7.0    3.0   1986.0
       2015-06-29 00:00:00 2549000.0        1.0    7.0    5.0   2009.0
       2017-08-24 00:00:00 1175000.0        1.0    6.0    3.0   2007.0
1794.0 2013-08-13 00:00:00 1550000.0        1.0    9.0    3.0   1986.0
       2017-05-24 00:00:00 5250000.0        1.0   11.0    6.0   1970.0
1796.0 2009-11-04 00:00:00 3330000.0        1.0   14.0    6.0   2009.0
       2011-11-01 00:00:00 3950000.0        1.0    8.0    3.0   2001.0
1800.0 1995-10-20 00:00:00 233000.0         NaN    5.0    1.0      NaN
       1997-10-20 00:00:00 339500.0         2.0    8.0    4.0   2009.0
       2005-06-07 00:00:00 220700.0         NaN    2.0    1.0   2004.0
       2005-06-15 00:00:00 166000.0         NaN    3.0    1.0   2004.0
       2005-06-29 00:00:00 155000.0         NaN    2.0    0.0   2004.0
       2006-08-28 00:00:00 1050000.0        2.0    9.0    4.0   1978.0
       2006-11-21 00:00:00 285000.0         1.0    4.0    2.0   1987.0
       2008-09-04 00:00:00 535000.0         1.0    6.0    2.0   2007.0
       2011-03-18 00:00:00 846000.0         2.0    9.0    4.0   2011.0
       2012-07-31 00:00:00 220000.0         NaN    2.0    0.0   2004.0
       2012-09-12 00:00:00 380000.0         NaN    3.0    1.0   2004.0
       2012-10-11 00:00:00 220000.0         NaN    2.0    0.0   2004.0
       2012-12-11 00:00:00 7000000.0        1.0   15.0    6.0   2012.0
       2013-05-03 00:00:00 270000.0         NaN    2.0    0.0   2004.0
       2013-05-16 00:00:00 322000.0         NaN    3.0    1.0   2004.0
       2013-06-13 00:00:00 235000.0         NaN    2.0    0.0   2004.0
...                                         ...    ...    ...      ...
2018.0 2018-05-04 00:00:00 462900.0         1.0    9.0    4.0      NaN
       2018-05-10 00:00:00 462900.0         1.0    9.0    4.0      NaN
                           464000.0         1.0    9.0    4.0      NaN
                           468000.0         1.0    9.0    4.0      NaN
       2018-05-14 00:00:00 803295.0         1.0    7.0    3.0      NaN
       2018-05-23 00:00:00 408855.0         1.0    8.0    3.0      NaN
       2018-05-31 00:00:00 460090.0         1.0   10.0    4.0      NaN
       2018-06-01 00:00:00 459900.0         1.0    9.0    3.0      NaN
                           1952500.0        1.0   10.0    6.0      NaN
       2018-06-06 00:00:00 438690.0         1.0    8.0    3.0      NaN
       2018-06-08 00:00:00 445155.0         1.0    8.0    3.0      NaN
       2018-06-19 00:00:00 435200.0         1.0    9.0    3.0      NaN
                           439900.0         1.0    9.0    3.0      NaN
                           457100.0         1.0    9.0    3.0      NaN
                           457700.0         1.0    9.0    3.0      NaN
       2018-06-21 00:00:00 419000.0         1.0    8.0    3.0      NaN
       2018-06-27 00:00:00 460385.0         1.0   10.0    3.0      NaN
                           462000.0         1.0   10.0    3.0      NaN
       2018-06-28 00:00:00 405000.0         1.0    9.0    4.0      NaN
                           435000.0         1.0    9.0    4.0      NaN
                           599000.0         1.0    8.0    4.0      NaN
       2018-06-29 00:00:00 457100.0         1.0    9.0    3.0      NaN
       2018-07-02 00:00:00 465600.0         1.0    8.0    3.0      NaN
       2018-07-03 00:00:00 451400.0         1.0    8.0    3.0      NaN
                           459900.0         1.0    8.0    3.0      NaN
       2018-07-05 00:00:00 449900.0         1.0    8.0    3.0      NaN
                           499900.0         1.0    8.0    3.0      NaN
       2018-07-09 00:00:00 479000.0         1.0    7.0    3.0      NaN
       2018-07-12 00:00:00 200000.0         1.0    8.0    4.0      NaN
                           560000.0         1.0    8.0    4.0      NaN

                                         EYB  STORIES  SALE_NUM    ...      \
AYB    SALEDATE            PRICE                                   ...
1754.0 2016-08-23 00:00:00 7100000.0  1991.0     3.00       3.0    ...
1765.0 2016-08-02 00:00:00 1100000.0  1983.0     2.50       4.0    ...
1776.0 1998-07-22 00:00:00 223500.0   1957.0     2.00       1.0    ...
       2009-04-17 00:00:00 725000.0   1967.0     2.00       1.0    ...
1780.0 2016-04-04 00:00:00 825000.0   1970.0     1.75       3.0    ...
       2016-09-22 00:00:00 660000.0   1919.0      NaN       2.0    ...
       2016-10-25 00:00:00 830000.0   1919.0      NaN       2.0    ...
1790.0 1996-01-19 00:00:00 812500.0   1976.0     3.00       1.0    ...
       2015-06-29 00:00:00 2549000.0  1983.0     2.00       3.0    ...
       2017-08-24 00:00:00 1175000.0  1978.0     2.00       7.0    ...
1794.0 2013-08-13 00:00:00 1550000.0  1970.0     2.00       1.0    ...
       2017-05-24 00:00:00 5250000.0  1986.0     3.00       2.0    ...
1796.0 2009-11-04 00:00:00 3330000.0  1996.0     2.00       1.0    ...
       2011-11-01 00:00:00 3950000.0  1992.0     2.50       1.0    ...
1800.0 1995-10-20 00:00:00 233000.0   1800.0      NaN       1.0    ...
       1997-10-20 00:00:00 339500.0   1967.0     3.00       1.0    ...
       2005-06-07 00:00:00 220700.0   1919.0      NaN       1.0    ...
       2005-06-15 00:00:00 166000.0   1919.0      NaN       1.0    ...
       2005-06-29 00:00:00 155000.0   1919.0      NaN       1.0    ...
       2006-08-28 00:00:00 1050000.0  1957.0     3.00       1.0    ...
       2006-11-21 00:00:00 285000.0   1954.0     2.00       1.0    ...
       2008-09-04 00:00:00 535000.0   1964.0     3.00       1.0    ...
       2011-03-18 00:00:00 846000.0   1964.0     3.00       1.0    ...
       2012-07-31 00:00:00 220000.0   1919.0      NaN       1.0    ...
       2012-09-12 00:00:00 380000.0   1919.0      NaN       1.0    ...
       2012-10-11 00:00:00 220000.0   1919.0      NaN       1.0    ...
       2012-12-11 00:00:00 7000000.0  1991.0     2.50       1.0    ...
       2013-05-03 00:00:00 270000.0   1919.0      NaN       1.0    ...
       2013-05-16 00:00:00 322000.0   1919.0      NaN       1.0    ...
       2013-06-13 00:00:00 235000.0   1919.0      NaN       1.0    ...
...                                      ...      ...       ...    ...
2018.0 2018-05-04 00:00:00 462900.0   2018.0     2.00       2.0    ...
       2018-05-10 00:00:00 462900.0   2018.0     2.00       2.0    ...
                           464000.0   2018.0     2.00       2.0    ...
                           468000.0   2018.0     2.00       2.0    ...
       2018-05-14 00:00:00 803295.0   2018.0     2.50       2.0    ...
       2018-05-23 00:00:00 408855.0   2018.0     2.00       3.0    ...
       2018-05-31 00:00:00 460090.0   2018.0     3.00       3.0    ...
       2018-06-01 00:00:00 459900.0   2018.0     3.00       3.0    ...
                           1952500.0  2018.0     3.00       3.0    ...
       2018-06-06 00:00:00 438690.0   2018.0     2.00       3.0    ...
       2018-06-08 00:00:00 445155.0   2018.0     3.00       3.0    ...
       2018-06-19 00:00:00 435200.0   2018.0     3.00       3.0    ...
                           439900.0   2018.0     3.00       3.0    ...
                           457100.0   2018.0     3.00       3.0    ...
                           457700.0   2018.0     3.00       3.0    ...
       2018-06-21 00:00:00 419000.0   2018.0     2.00       3.0    ...
       2018-06-27 00:00:00 460385.0   2018.0     3.00       3.0    ...
                           462000.0   2018.0     3.00       3.0    ...
       2018-06-28 00:00:00 405000.0   2018.0     3.00       2.0    ...
                           435000.0   2018.0     3.00       2.0    ...
                           599000.0   2018.0     2.00       2.0    ...
       2018-06-29 00:00:00 457100.0   2018.0     3.00       3.0    ...
       2018-07-02 00:00:00 465600.0   2018.0     3.00       3.0    ...
       2018-07-03 00:00:00 451400.0   2018.0     3.00       2.0    ...
                           459900.0   2018.0     3.00       2.0    ...
       2018-07-05 00:00:00 449900.0   2018.0     3.00       2.0    ...
                           499900.0   2018.0     3.00       2.0    ...
       2018-07-09 00:00:00 479000.0   2018.0     2.00       3.0    ...
       2018-07-12 00:00:00 200000.0   2018.0     1.00       2.0    ...
                           560000.0   2018.0     2.00       2.0    ...

                                      USECODE  LANDAREA  CMPLX_NUM  \
AYB    SALEDATE            PRICE
1754.0 2016-08-23 00:00:00 7100000.0     12.0   24164.0        NaN
1765.0 2016-08-02 00:00:00 1100000.0     13.0     840.0        NaN
1776.0 1998-07-22 00:00:00 223500.0      24.0    1611.0        NaN
       2009-04-17 00:00:00 725000.0      11.0    1605.0        NaN
1780.0 2016-04-04 00:00:00 825000.0      11.0    1152.0        NaN
       2016-09-22 00:00:00 660000.0      16.0     968.0     5372.0
       2016-10-25 00:00:00 830000.0      16.0     968.0     5372.0
1790.0 1996-01-19 00:00:00 812500.0      11.0    2400.0        NaN
       2015-06-29 00:00:00 2549000.0     11.0    2736.0        NaN
       2017-08-24 00:00:00 1175000.0     13.0    1570.0        NaN
1794.0 2013-08-13 00:00:00 1550000.0     11.0    4299.0        NaN
       2017-05-24 00:00:00 5250000.0     12.0    7765.0        NaN
1796.0 2009-11-04 00:00:00 3330000.0     12.0   11230.0        NaN
       2011-11-01 00:00:00 3950000.0     13.0    3403.0        NaN
1800.0 1995-10-20 00:00:00 233000.0      16.0     650.0     2398.0
       1997-10-20 00:00:00 339500.0      24.0    1853.0        NaN
       2005-06-07 00:00:00 220700.0      17.0     249.0     2672.0
       2005-06-15 00:00:00 166000.0      17.0     288.0     2672.0
       2005-06-29 00:00:00 155000.0      17.0     229.0     2672.0
       2006-08-28 00:00:00 1050000.0     24.0    1853.0        NaN
       2006-11-21 00:00:00 285000.0      12.0    1409.0        NaN
       2008-09-04 00:00:00 535000.0      11.0    1035.0        NaN
       2011-03-18 00:00:00 846000.0      24.0    1971.0        NaN
       2012-07-31 00:00:00 220000.0      17.0     241.0     2672.0
       2012-09-12 00:00:00 380000.0      17.0     464.0     2672.0
       2012-10-11 00:00:00 220000.0      17.0     232.0     2672.0
       2012-12-11 00:00:00 7000000.0     12.0   14716.0        NaN
       2013-05-03 00:00:00 270000.0      17.0     252.0     2672.0
       2013-05-16 00:00:00 322000.0      17.0     298.0     2672.0
       2013-06-13 00:00:00 235000.0      17.0     232.0     2672.0
...                                       ...       ...        ...
2018.0 2018-05-04 00:00:00 462900.0      11.0    3200.0        NaN
       2018-05-10 00:00:00 462900.0      11.0    3200.0        NaN
                           464000.0      11.0    3200.0        NaN
                           468000.0      11.0    3200.0        NaN
       2018-05-14 00:00:00 803295.0      11.0    3158.0        NaN
       2018-05-23 00:00:00 408855.0      11.0    1239.0        NaN
       2018-05-31 00:00:00 460090.0      11.0    1239.0        NaN
       2018-06-01 00:00:00 459900.0      11.0    4000.0        NaN
                           1952500.0     12.0    4335.0        NaN
       2018-06-06 00:00:00 438690.0      11.0    2034.0        NaN
       2018-06-08 00:00:00 445155.0      11.0    2045.0        NaN
       2018-06-19 00:00:00 435200.0      11.0    2000.0        NaN
                           439900.0      11.0    2000.0        NaN
                           457100.0      11.0    2000.0        NaN
                           457700.0      11.0    2000.0        NaN
       2018-06-21 00:00:00 419000.0      11.0    2043.0        NaN
       2018-06-27 00:00:00 460385.0      11.0    1232.0        NaN
                           462000.0      11.0    1246.0        NaN
       2018-06-28 00:00:00 405000.0      11.0    2000.0        NaN
                           435000.0      11.0    2000.0        NaN
                           599000.0      12.0    4221.0        NaN
       2018-06-29 00:00:00 457100.0      11.0    2000.0        NaN
       2018-07-02 00:00:00 465600.0      11.0    3379.0        NaN
       2018-07-03 00:00:00 451400.0      11.0    2989.0        NaN
                           459900.0      11.0    3641.0        NaN
       2018-07-05 00:00:00 449900.0      11.0    2920.0        NaN
                           499900.0      11.0    2886.0        NaN
       2018-07-09 00:00:00 479000.0      11.0    2850.0        NaN
       2018-07-12 00:00:00 200000.0      13.0    5098.0        NaN
                           560000.0      12.0    5009.0        NaN

                                      LIVING_GBA  ZIPCODE   LATITUDE  \
AYB    SALEDATE            PRICE
1754.0 2016-08-23 00:00:00 7100000.0         NaN  20008.0  38.918175
1765.0 2016-08-02 00:00:00 1100000.0         NaN  20007.0  38.909667
1776.0 1998-07-22 00:00:00 223500.0          NaN  20003.0  38.884904
       2009-04-17 00:00:00 725000.0          NaN  20003.0  38.884894
1780.0 2016-04-04 00:00:00 825000.0          NaN  20007.0  38.905919
       2016-09-22 00:00:00 660000.0       1630.0  20002.0  38.901929
       2016-10-25 00:00:00 830000.0       1322.0  20002.0  38.901929
1790.0 1996-01-19 00:00:00 812500.0          NaN  20007.0  38.908666
       2015-06-29 00:00:00 2549000.0         NaN  20007.0  38.908672
       2017-08-24 00:00:00 1175000.0         NaN  20007.0  38.907619
1794.0 2013-08-13 00:00:00 1550000.0         NaN  20007.0  38.907032
       2017-05-24 00:00:00 5250000.0         NaN  20007.0  38.907063
1796.0 2009-11-04 00:00:00 3330000.0         NaN  20008.0  38.940542
       2011-11-01 00:00:00 3950000.0         NaN  20007.0  38.906985
1800.0 1995-10-20 00:00:00 233000.0       1194.0  20007.0  38.909983
       1997-10-20 00:00:00 339500.0          NaN  20009.0  38.911701
       2005-06-07 00:00:00 220700.0        444.0  20003.0  38.883630
       2005-06-15 00:00:00 166000.0        511.0  20003.0  38.883630
       2005-06-29 00:00:00 155000.0        410.0  20003.0  38.883630
       2006-08-28 00:00:00 1050000.0         NaN  20009.0  38.911706
       2006-11-21 00:00:00 285000.0          NaN  20001.0  38.906625
       2008-09-04 00:00:00 535000.0          NaN  20003.0  38.884533
       2011-03-18 00:00:00 846000.0          NaN  20009.0  38.911716
       2012-07-31 00:00:00 220000.0        434.0  20003.0  38.883630
       2012-09-12 00:00:00 380000.0        866.0  20003.0  38.883630
       2012-10-11 00:00:00 220000.0        422.0  20003.0  38.883630
       2012-12-11 00:00:00 7000000.0         NaN  20007.0  38.907828
       2013-05-03 00:00:00 270000.0        453.0  20003.0  38.883630
       2013-05-16 00:00:00 322000.0        542.0  20003.0  38.883630
       2013-06-13 00:00:00 235000.0        414.0  20003.0  38.883630
...                                          ...      ...        ...
2018.0 2018-05-04 00:00:00 462900.0          NaN  20020.0  38.862353
       2018-05-10 00:00:00 462900.0          NaN  20020.0  38.862428
                           464000.0          NaN  20020.0  38.862388
                           468000.0          NaN  20020.0  38.862317
       2018-05-14 00:00:00 803295.0          NaN  20018.0  38.924568

In [13]:
df['PRICE'].groupby(df['ZIPCODE']).mean()

ZIPCODE
20001.0    5.215550e+05
20002.0    4.628894e+05
20003.0    5.992484e+05
20004.0    4.755701e+05
20005.0    2.813137e+06
20006.0    1.959069e+05
20007.0    9.794061e+05
20008.0    8.522766e+05
20009.0    6.215259e+05
20010.0    5.070154e+05
20011.0    4.259763e+05
20012.0    4.755227e+05
20015.0    7.703746e+05
20016.0    5.914537e+06
20017.0    4.087405e+05
20018.0    3.691101e+05
20019.0    2.302621e+05
20020.0    2.281464e+05
20024.0    3.808846e+05
20032.0    3.235769e+05
20036.0    4.015452e+05
20037.0    6.124601e+05
20052.0    5.378571e+05
20392.0    3.489169e+05
Name: PRICE, dtype: float64

In [14]:
df['PRICE'].groupby(df['YR_RMDL']).mean()

YR_RMDL
20.0      3.350000e+05
1880.0    5.700000e+05
1900.0    4.150000e+05
1910.0    3.300000e+05
1911.0             NaN
1912.0             NaN
1913.0             NaN
1915.0             NaN
1916.0             NaN
1917.0    2.860000e+05
1920.0    2.025000e+05
1921.0    2.990000e+05
1922.0    4.500000e+05
1923.0    9.000000e+04
1924.0             NaN
1925.0    2.165000e+05
1926.0    7.537500e+05
1927.0    4.150083e+05
1928.0    3.999500e+05
1929.0    3.439275e+05
1930.0    9.500000e+05
1931.0    2.030050e+05
1932.0    1.000000e+06
1933.0             NaN
1934.0    1.595000e+06
1935.0    5.862500e+05
1936.0    4.700000e+05
1937.0             NaN
1938.0             NaN
1939.0    2.657500e+05
              ...
1990.0    6.295934e+05
1991.0    4.198709e+05
1992.0    5.477510e+05
1993.0    4.489786e+05
1994.0    5.888261e+05
1995.0    6.939913e+05
1996.0    5.459179e+05
1997.0    6.738446e+05
1998.0    6.770932e+05
1999.0    7.503437e+05
2000.0    6.387522e+05
2001.0    7.860214e+05
2002.0    6.602012e+05
2003.0    5.337447e+05
2004.0    5.511114e+05
2005.0    8.971842e+06
2006.0    2.097879e+06
2007.0    5.427228e+05
2008.0    6.200020e+05
2009.0    6.466379e+05
2010.0    6.007152e+05
2011.0    6.138181e+05
2012.0    6.659832e+05
2013.0    6.940434e+05
2014.0    6.897668e+05
2015.0    6.952223e+05
2016.0    7.097580e+05
2017.0    7.610305e+05
2018.0    6.281237e+05
2019.0    5.649500e+05
Name: PRICE, Length: 110, dtype: float64

In [15]:
#multiple conditions
df.loc[(df['YR_RMDL'] >= 2007) & (df['YR_RMDL'] < 2017) & (df['PRICE'] >= 400000) & (df['PRICE'] < 800000)] #between year 2007 and 2017

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
45,45,3,1,Forced Air,Y,2.0,10,5,1890.0,2009.0,...,-77.032744,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
55,55,3,1,Forced Air,Y,2.0,8,3,1890.0,2007.0,...,-77.033767,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
69,69,3,1,Hot Water Rad,N,3.0,10,4,1885.0,2009.0,...,-77.034889,Old City 2,040 E Old City 2,5201.0,005201 2000,Ward 2,192,-77.034848,38.913055,NW
73,73,2,1,Warm Cool,Y,1.0,7,2,1907.0,2011.0,...,-77.038227,Old City 2,040 D Old City 2,4201.0,004201 1002,Ward 2,176,-77.037830,38.916190,NW
97,97,4,0,Warm Cool,Y,4.0,12,4,1900.0,2013.0,...,-77.046406,Old City 2,040 D Old City 2,5500.0,005500 1001,Ward 2,92,-77.046148,38.913145,NW
101,101,4,1,Warm Cool,Y,2.0,11,5,1887.0,2015.0,...,-77.045991,Old City 2,040 D Old City 2,5500.0,005500 1001,Ward 2,92,-77.046148,38.913145,NW
133,133,3,1,Warm Cool,Y,1.0,9,3,1908.0,2008.0,...,-77.040432,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
148,148,2,1,Warm Cool,Y,1.0,5,2,1939.0,2007.0,...,-77.042040,Old City 2,040 D Old City 2,4202.0,004202 1008,Ward 2,134,-77.042719,38.912019,NW
161,161,1,1,Warm Cool,Y,1.0,6,3,1880.0,2013.0,...,-77.039217,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
163,163,1,1,Warm Cool,Y,1.0,6,3,1880.0,2011.0,...,-77.039111,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
205,205,3,0,Warm Cool,Y,2.0,9,3,1890.0,2009.0,...,-77.037577,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
253,253,3,1,Hot Water Rad,N,2.0,13,7,1890.0,2011.0,...,-77.046372,Old City 2,040 D Old City 2,5500.0,005500 1004,Ward 2,93,-77.045889,38.912003,NW
271,271,1,0,Forced Air,Y,1.0,4,2,1900.0,2009.0,...,-77.053103,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
279,279,2,0,Warm Cool,Y,1.0,6,3,1880.0,2016.0,...,-77.038797,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
297,297,2,0,Warm Cool,Y,1.0,7,4,1820.0,2008.0,...,-77.039873,Old City 2,040 D Old City 2,4201.0,004201 2001,Ward 1,150,-77.039567,38.917462,NW
307,307,1,1,Warm Cool,Y,1.0,6,3,1900.0,2014.0,...,-77.039613,Old City 2,040 D Old City 2,4201.0,004201 2001,Ward 1,150,-77.039567,38.917462,NW
316,316,4,2,Forced Air,Y,2.0,13,5,1880.0,2008.0,...,-77.033072,Old City 2,040 E Old City 2,5201.0,005201 4004,Ward 2,209,-77.033446,38.910498,NW
332,332,1,0,Forced Air,Y,1.0,8,4,1895.0,2007.0,...,-77.030461,Old City 2,040 F Old City 2,4400.0,004400 1005,Ward 1,234,-77.030839,38.919956,NW
384,384,2,0,Warm Cool,Y,1.0,7,2,1900.0,2007.0,...,-77.053007,Foggy Bottom,NaN,5600.0,005600 4003,Ward 2,29,-77.052880,38.900288,NW
419,419,2,0,Hot Water Rad,Y,1.0,7,3,1926.0,2008.0,...,-77.049045,Central-tri 1,NaN,5500.0,005500 2004,Ward 2,49,-77.049045,38.908130,NW
422,422,2,1,Hot Water Rad,N,2.0,6,3,1907.0,2014.0,...,-77.039520,Old City 2,040 D Old City 2,4201.0,004201 2001,Ward 1,150,-77.039567,38.917462,NW
427,427,3,0,Warm Cool,Y,2.0,8,5,1909.0,2008.0,...,-77.039410,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
430,430,4,0,Hot Water Rad,Y,1.0,10,4,1910.0,2008.0,...,-77.039591,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
445,445,1,1,Warm Cool,Y,1.0,6,3,1900.0,2011.0,...,-77.040284,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
456,456,2,1,Warm Cool,Y,1.0,6,3,1900.0,2012.0,...,-77.039666,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
468,468,5,3,Hot Water Rad,Y,3.0,12,8,1895.0,2010.0,...,-77.030866,Old City 2,040 F Old City 2,4400.0,004400 1006,Ward 1,235,-77.030790,38.918755,NW
472,472,1,1,Forced Air,Y,1.0,6,2,1908.0,2008.0,...,-77.030398,Old City 2,040 F Old City 2,4400.0,004400 1006,Ward 1,235,-77.030790,38.918755,NW
473,473,1,1,Forced Air,Y,1.0,6,2,1908.0,2008.0,...,-77.030450,Old City 2,040 F Old City 2,4400.0,004400 1006,Ward 1,235,-77.030790,38.918755,NW
474,474,1,1,Forced Air,Y,1.0,7,2,1908.0,2008.0,...,-77.030503,Old City 2,040 F Old City 2,4400.0,004400 1006,Ward 1,235,-77.030790,38.918755,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155908,155908,3,0,Forced Air,Y,NaN,6,3,1900.0,2013.0,...,-77.020723,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,445,-77.020725,38.910531,NW
155909,155909,2,0,Forced Air,Y,NaN,4,2,1900.0,2013.0,...,-77.020723,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,445,-77.020725,38.910531,NW
156101,156101,3,1,Forced Air,Y,NaN,6,4,1900.0,2011.0,...,-77.018148,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,511,-77.018150,38.909072,NW
156102,156102,2,0,Forced Air,Y,NaN,4,2,1900.0,2011.0,...,-77.018148,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,511,-77.018150,38.909072,NW
156103,156103,2,0,Forced Air,Y,NaN,4,2,1900.0,2011.0,...,-77.018148,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,511,-77.018150,38.909072,NW
156104,156104,2,1,Forced Air,Y,NaN,6,2,1900.0,2013.0,...,-77.018148,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,511,-77.018150,38.909072,NW
156105,156105,2,1,Forced Air,Y,NaN,5,2,1900.0,2013.0,...,-77.018148,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,511,-77.018150,38.909072,NW
156413,156413,2,0,Warm Cool,Y,NaN,3,2,1965.0,2010.0,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
156497,156497,2,1,Ht Pump,Y,NaN,6,3,1961.0,2016.0,...,-77.014271,Southwest Waterfront,NaN,10500.0,NaN,Ward 6,540,-77.014273,38.880828,SW
156779,156779,2,0,Elec Base Brd,Y,NaN,5,2,1960.0,2009.0,...,-77.016943,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,542,-77.016945,38.877546,SW
156780,156780,1,0,Elec Base Brd,Y,NaN,4,2,1960.0,2009.0,...,-77.016943,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,542,-77.016945,38.877546,SW
157652,157652,1,0,Elec Base Brd,Y,NaN,3,1,1960.0,2009.0,...,-77.016943,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,542,-77.016945,38.877546,SW
157654,157654,1,0,Elec Base Brd,Y,NaN,4,2,1960.0,2009.0,...,-77.016943,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,542,-77.016945,38.877546,SW
157921,157921,2,0,Elec Base Brd,Y,NaN,5,3,1960.0,2009.0,...,-77.016943,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,542,-77.016945,38.877546,SW
157996,157996,1,0,Forced Air,Y,NaN,3,1,1900.0,2013.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
157999,157999,2,1,Forced Air,Y,NaN,4,2,1890.0,2013.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158000,158000,2,1,Forced Air,Y,NaN,4,2,1890.0,2013.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158001,158001,2,0,Forced Air,Y,NaN,4,2,1900.0,2016.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158002,158002,2,0,Forced Air,Y,NaN,4,2,1900.0,2016.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158003,158003,2,0,Forced Air,Y,NaN,4,2,1900.0,2016.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158005,158005,2,1,Forced Air,Y,NaN,4,2,1900.0,2016.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158006,158006,2,0,Forced Air,Y,NaN,4,2,1900.0,2016.0,...,-77.017406,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,513,-77.017409,38.906576,NW
158080,158080,2,1,Warm Cool,Y,NaN,5,2,1965.0,2015.0,...,-77.018649,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,502,-77.018651,38.875672,SW
158262,158262,2,1,Forced Air,Y,NaN,4,2,1890.0,2007.0,...,-77.018312,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,514,-77.018315,38.905417,NW
158266,158266,2,0,Forced Air,Y,NaN,4,2,1890.0,2007.0,...,-77.018312,Old City 2,040 B Old City 2,4802.0,NaN,Ward 6,514,-77.018315,38.905417,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW

In [16]:
df.fillna(0)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,0.0,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,0.0,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,0.0,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,0,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,0.0,5,2,2013.0,0.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,0,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,0.0,5,2,2013.0,0.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,0,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,0.0,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,0.0,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,0.0,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,0.0,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,0.0,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,0.0,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,0.0,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,0,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,0.0,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,0.0,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,0.0,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,0.0,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,0.0,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,0.0,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,0.0,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,0.0,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,0.0,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,0.0,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,0.0,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,0.0,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,0.0,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,0.0,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,0.0,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,0.0,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,0.0,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,0.0,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,0,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,0.0,2,0,1965.0,0.0,...,-77.018230,Southwest Waterfront,0,11000.0,0,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,0.0,2,0,1965.0,0.0,...,-77.018230,Southwest Waterfront,0,11000.0,0,Ward 6,504,-77.018232,38.872961,SW

In [17]:
dupe = df.duplicated() #creates list of True/False values
df[dupe] #shows rows where duplicated is True

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [18]:
df2= df [['YR_RMDL','FULLADDRESS','SALEDATE','PRICE']]
df2

        YR_RMDL                   FULLADDRESS             SALEDATE      PRICE
0        1988.0          1748 SWANN STREET NW  2003-11-25 00:00:00  1095000.0
1        2007.0          1746 SWANN STREET NW  2000-08-17 00:00:00        NaN
2        2009.0          1744 SWANN STREET NW  2016-06-21 00:00:00  2100000.0
3        2003.0          1742 SWANN STREET NW  2006-07-12 00:00:00  1602000.0
4        2012.0  1804 NEW HAMPSHIRE AVENUE NW                  NaN        NaN
5           NaN              1709 S STREET NW  2010-02-26 00:00:00  1950000.0
6        1988.0          1769 SWANN STREET NW  2011-05-02 00:00:00        NaN
7        2011.0          1746 1/2 T STREET NW  2011-09-29 00:00:00  1050000.0
8        2008.0          1727 SWANN STREET NW  2018-05-03 00:00:00  1430000.0
9        1979.0          1733 SWANN STREET NW  2008-12-05 00:00:00        NaN
10       1950.0          1755 SWANN STREET NW                  NaN        NaN
11          NaN              1734 T STREET NW  2009-03-12 00:00:00        NaN
12       1979.0          1717 SWANN STREET NW                  NaN        NaN
13       1979.0      1719 1/2 SWANN STREET NW                  NaN        NaN
14       2000.0          1721 SWANN STREET NW  2011-09-30 00:00:00  1325000.0
15       1990.0          1723 SWANN STREET NW                  NaN        NaN
16       2006.0          1725 SWANN STREET NW  2010-11-04 00:00:00  1240000.0
17       1987.0          1729 SWANN STREET NW  2008-05-08 00:00:00        NaN
18       2006.0          1731 SWANN STREET NW  2016-08-18 00:00:00        NaN
19       2013.0          1735 SWANN STREET NW  2001-07-23 00:00:00   592250.0
20       2009.0              1441 Q STREET NW  2016-01-12 00:00:00    33232.0
21       2009.0              1443 Q STREET NW  2014-04-30 00:00:00        NaN
22       2010.0              1445 Q STREET NW  2006-01-09 00:00:00   907400.0
23       2010.0              1447 Q STREET NW  2012-08-21 00:00:00  1065000.0
24       2004.0              1449 Q STREET NW  2012-07-25 00:00:00  1100000.0
25       2010.0              1451 Q STREET NW  1996-04-02 00:00:00    20000.0
26       2004.0       1458 CORCORAN STREET NW                  NaN        NaN
27       1963.0       1456 CORCORAN STREET NW  2005-04-06 00:00:00   703700.0
28       1960.0       1454 CORCORAN STREET NW  2015-02-06 00:00:00        NaN
29       2014.0       1452 CORCORAN STREET NW  2013-12-11 00:00:00  1210000.0
...         ...                           ...                  ...        ...
158927   1993.0                           NaN  2015-10-07 00:00:00        NaN
158928      NaN                           NaN  2017-05-24 00:00:00   632400.0
158929      NaN                           NaN  2012-12-19 00:00:00   574000.0
158930   2003.0                           NaN  2007-06-25 00:00:00   365000.0
158931   2003.0                           NaN  2005-07-06 00:00:00   405000.0
158932   2003.0                           NaN  2014-07-09 00:00:00   505000.0
158933   2016.0                           NaN  2017-01-12 00:00:00   520000.0
158934   2016.0                           NaN  2017-02-23 00:00:00   499900.0
158935   2016.0                           NaN  2016-12-28 00:00:00   451000.0
158936   2016.0                           NaN  2016-12-28 00:00:00   564900.0
158937   1992.0                           NaN                  NaN        NaN
158938   1992.0                           NaN  2015-03-02 00:00:00   660000.0
158939   1992.0                           NaN  2016-09-30 00:00:00   380000.0
158940   1992.0                           NaN  2008-06-04 00:00:00        NaN
158941   1992.0                           NaN                  NaN        NaN
158942   1992.0                           NaN                  NaN        NaN
158943   2004.0                           NaN  2004-11-08 00:00:00   539000.0
158944   2004.0                           NaN  2016-07-19 00:00:00   908500.0
158945   2006.0                           NaN  2006-07-13 00:00:00   450000.0
158946   2006.0                           NaN  2015-02-11 00:00:00   485355.0
158947   2006.0                           NaN  2008-06-30 00:00:00   320000.0
158948   2006.0                           NaN  2012-10-22 00:00:00   460000.0
158949   2006.0                           NaN  2015-06-09 00:00:00   550000.0
158950   2006.0                           NaN  2015-12-24 00:00:00   635000.0
158951   2006.0                           NaN  2009-11-12 00:00:00   389000.0
158952   2006.0                           NaN  2015-04-03 00:00:00   399900.0
158953   2006.0                           NaN  2013-10-04 00:00:00   416000.0
158954   2007.0                           NaN  2008-09-30 00:00:00   600000.0
158955      NaN                           NaN  2015-04-14 00:00:00   215100.0
158956      NaN                           NaN  2002-07-22 00:00:00        NaN

[158957 rows x 4 columns]

In [21]:
df3=df2.loc[(df2['PRICE'] >= 5000000)] 
df3

        YR_RMDL                   FULLADDRESS             SALEDATE       PRICE
2149     2005.0  1714 MASSACHUSETTS AVENUE NW  2009-11-30 00:00:00  11984000.0
2556     2005.0              1824 R STREET NW  2014-02-14 00:00:00   8450000.0
3303        NaN                10 N STREET SW  2015-08-24 00:00:00  11000000.0
18177    2007.0      2613 DUMBARTON STREET NW  2018-06-27 00:00:00   5000000.0
18350    2014.0              3249 N STREET NW  2013-01-25 00:00:00   7550000.0
18585    2009.0              3024 Q STREET NW  2017-05-11 00:00:00   6750000.0
18853    2001.0           1315 31ST STREET NW  2010-04-15 00:00:00   5450000.0
18869    2002.0              3323 P STREET NW  2016-02-05 00:00:00   5700000.0
18870    2008.0              3327 P STREET NW  2011-04-25 00:00:00   6750000.0
18871       NaN              3327 P STREET NW  2011-04-25 00:00:00   6750000.0
19019    2000.0              3053 P STREET NW  2018-01-17 00:00:00   7365000.0
19110    2012.0      3123 DUMBARTON STREET NW  2012-12-11 00:00:00   7000000.0
19304    1970.0              3017 N STREET NW  2017-05-24 00:00:00   5250000.0
19435    2015.0           1319 30TH STREET NW  2015-10-26 00:00:00   5100000.0
19544       NaN       3325 PROSPECT STREET NW  2014-05-19 00:00:00   5230000.0
19594    2012.0           1515 31ST STREET NW  2017-12-15 00:00:00   5600000.0
19630    1962.0              3300 O STREET NW  2014-12-29 00:00:00   5000000.0
19707    2015.0                           NaN  2013-07-11 00:00:00   7850000.0
19894    2014.0           1309 29TH STREET NW  2016-06-08 00:00:00   6300000.0
20035    2009.0              3121 O STREET NW  2003-04-25 00:00:00   5175000.0
20036    2009.0              3121 O STREET NW  2003-04-25 00:00:00   5175000.0
20041    2006.0              3124 P STREET NW  2018-07-03 00:00:00   5650000.0
20065    2008.0              3306 O STREET NW  2004-10-18 00:00:00   5100000.0
20164    2004.0              3124 Q STREET NW  2007-05-02 00:00:00  23960287.0
20329    2012.0           1231 31ST STREET NW  2014-11-17 00:00:00   5200000.0
20331    2014.0              3028 N STREET NW  2013-08-27 00:00:00   5400000.0
20351    2014.0           1525 29TH STREET NW  2017-04-10 00:00:00   5250000.0
20685    2013.0           1623 28TH STREET NW  2011-07-25 00:00:00  22000000.0
20887    2008.0              3017 O STREET NW  2007-12-27 00:00:00   7500000.0
20936    2013.0              3210 R STREET NW  2010-12-09 00:00:00  11111111.0
...         ...                           ...                  ...         ...
142446      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142447      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142448      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142449      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142450      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142451      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142452      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142453      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142454      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142455      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142456      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142457      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142458      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142459      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142460      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142461      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142462      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142463      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142464      NaN                           NaN  2017-06-14 00:00:00  12780000.0
142465      NaN                           NaN  2017-06-14 00:00:00  12780000.0
146495      NaN                           NaN  2008-10-03 00:00:00   5700000.0
148308   2006.0                           NaN  2006-09-21 00:00:00  14157126.0
149061      NaN                           NaN  2017-05-04 00:00:00   6500000.0
153483   2017.0                           NaN  2018-05-17 00:00:00   5995000.0
153487   2017.0                           NaN  2017-05-09 00:00:00   8400000.0
153963      NaN                           NaN  2005-06-16 00:00:00   5394400.0
153967      NaN                           NaN  2005-06-16 00:00:00   5394400.0
153971      NaN                           NaN  2005-06-16 00:00:00   5394400.0
154210      NaN                           NaN  2005-06-16 00:00:00   5394400.0
154214      NaN                           NaN  2005-06-16 00:00:00   5394400.0

[583 rows x 4 columns]

In [20]:
df3.fillna(0)

        YR_RMDL                   FULLADDRESS             SALEDATE       PRICE
2149     2005.0  1714 MASSACHUSETTS AVENUE NW  2009-11-30 00:00:00  11984000.0
2556     2005.0              1824 R STREET NW  2014-02-14 00:00:00   8450000.0
3303        0.0                10 N STREET SW  2015-08-24 00:00:00  11000000.0
18177    2007.0      2613 DUMBARTON STREET NW  2018-06-27 00:00:00   5000000.0
18350    2014.0              3249 N STREET NW  2013-01-25 00:00:00   7550000.0
18585    2009.0              3024 Q STREET NW  2017-05-11 00:00:00   6750000.0
18853    2001.0           1315 31ST STREET NW  2010-04-15 00:00:00   5450000.0
18869    2002.0              3323 P STREET NW  2016-02-05 00:00:00   5700000.0
18870    2008.0              3327 P STREET NW  2011-04-25 00:00:00   6750000.0
18871       0.0              3327 P STREET NW  2011-04-25 00:00:00   6750000.0
19019    2000.0              3053 P STREET NW  2018-01-17 00:00:00   7365000.0
19110    2012.0      3123 DUMBARTON STREET NW  2012-12-11 00:00:00   7000000.0
19304    1970.0              3017 N STREET NW  2017-05-24 00:00:00   5250000.0
19435    2015.0           1319 30TH STREET NW  2015-10-26 00:00:00   5100000.0
19544       0.0       3325 PROSPECT STREET NW  2014-05-19 00:00:00   5230000.0
19594    2012.0           1515 31ST STREET NW  2017-12-15 00:00:00   5600000.0
19630    1962.0              3300 O STREET NW  2014-12-29 00:00:00   5000000.0
19707    2015.0                             0  2013-07-11 00:00:00   7850000.0
19894    2014.0           1309 29TH STREET NW  2016-06-08 00:00:00   6300000.0
20035    2009.0              3121 O STREET NW  2003-04-25 00:00:00   5175000.0
20036    2009.0              3121 O STREET NW  2003-04-25 00:00:00   5175000.0
20041    2006.0              3124 P STREET NW  2018-07-03 00:00:00   5650000.0
20065    2008.0              3306 O STREET NW  2004-10-18 00:00:00   5100000.0
20164    2004.0              3124 Q STREET NW  2007-05-02 00:00:00  23960287.0
20329    2012.0           1231 31ST STREET NW  2014-11-17 00:00:00   5200000.0
20331    2014.0              3028 N STREET NW  2013-08-27 00:00:00   5400000.0
20351    2014.0           1525 29TH STREET NW  2017-04-10 00:00:00   5250000.0
20685    2013.0           1623 28TH STREET NW  2011-07-25 00:00:00  22000000.0
20887    2008.0              3017 O STREET NW  2007-12-27 00:00:00   7500000.0
20936    2013.0              3210 R STREET NW  2010-12-09 00:00:00  11111111.0
...         ...                           ...                  ...         ...
142446      0.0                             0  2017-06-14 00:00:00  12780000.0
142447      0.0                             0  2017-06-14 00:00:00  12780000.0
142448      0.0                             0  2017-06-14 00:00:00  12780000.0
142449      0.0                             0  2017-06-14 00:00:00  12780000.0
142450      0.0                             0  2017-06-14 00:00:00  12780000.0
142451      0.0                             0  2017-06-14 00:00:00  12780000.0
142452      0.0                             0  2017-06-14 00:00:00  12780000.0
142453      0.0                             0  2017-06-14 00:00:00  12780000.0
142454      0.0                             0  2017-06-14 00:00:00  12780000.0
142455      0.0                             0  2017-06-14 00:00:00  12780000.0
142456      0.0                             0  2017-06-14 00:00:00  12780000.0
142457      0.0                             0  2017-06-14 00:00:00  12780000.0
142458      0.0                             0  2017-06-14 00:00:00  12780000.0
142459      0.0                             0  2017-06-14 00:00:00  12780000.0
142460      0.0                             0  2017-06-14 00:00:00  12780000.0
142461      0.0                             0  2017-06-14 00:00:00  12780000.0
142462      0.0                             0  2017-06-14 00:00:00  12780000.0
142463      0.0                             0  2017-06-14 00:00:00  12780000.0
142464      0.0                             0  2017-06-14 00:00:00  12780000.0
142465      0.0                             0  2017-06-14 00:00:00  12780000.0
146495      0.0                             0  2008-10-03 00:00:00   5700000.0
148308   2006.0                             0  2006-09-21 00:00:00  14157126.0
149061      0.0                             0  2017-05-04 00:00:00   6500000.0
153483   2017.0                             0  2018-05-17 00:00:00   5995000.0
153487   2017.0                             0  2017-05-09 00:00:00   8400000.0
153963      0.0                             0  2005-06-16 00:00:00   5394400.0
153967      0.0                             0  2005-06-16 00:00:00   5394400.0
153971      0.0                             0  2005-06-16 00:00:00   5394400.0
154210      0.0                             0  2005-06-16 00:00:00   5394400.0
154214      0.0                             0  2005-06-16 00:00:00   5394400.0

[583 rows x 4 columns]

In [ ]:
#The data had 158957 rows and 49 columns. There were no duplicates in the data. 
#I ran analysis to find mean for the Price which was $931351.6 and the highest price for house was $137427545.0.  
#I applied multiple conditions to generate data with year remodeled between year 2007 and 2017; and price between $400000 and $80000 to make the data smaller, which generated a new table with 8858 rows Ã— 49 columns.
#I used groupby to group price by year remodelled and price by zipcode.I generated table with fewer variables (year remodelled, full address, saledate and price). I generated table which had prices of houses more than $5000000, and also filled in the null values with 0.